/*

Copyright (C) 2011 huchifeng@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONTACT: huchifeng@gmail.com
HOMEPAGE: https://github.com/huchifeng/huchifeng

*/
/*
NtQueryVolumeInformationFile
  volume id, changed after every formatting


*/

#include <time.h>
#include <iostream>
#include <vector>
#include <assert.h>
#include <windows.h>
#include <process.h>

using namespace std;

long common = 0;
long res1 = 0;
long res2 = 0;

unsigned __stdcall thread_main_1( void * ){
	res1 = InterlockedIncrement(&common); // correct
	// InterlockedIncrement(&common); Sleep(1); res1 = common; // wrong // add sleep to make it fail quickly
	return 0;
}
unsigned __stdcall thread_main_2( void * ){
	res2 = InterlockedIncrement(&common);
	// InterlockedIncrement(&common); Sleep(1); res2 = common;// wrong
	return 0;
}

void main(){
	// If the thread generated by _beginthread exits quickly, the handle returned to the caller of _beginthread might be invalid or,
	//    worse, point to another thread

	// the handle returned by _beginthreadex has to be closed by the caller of _beginthreadex,
	//    so it is guaranteed to be a valid handle if _beginthreadex did not return an error.
	while(1){
		common = res1 = res2 = 0;
		HANDLE h1 = (HANDLE)_beginthreadex(NULL, 0, thread_main_1, NULL, CREATE_SUSPENDED, NULL);
		HANDLE h2 = (HANDLE)_beginthreadex(NULL, 0, thread_main_2, NULL, 0, NULL);
		ResumeThread(h1);
		WaitForSingleObject(h1, INFINITE);
		CloseHandle(h1);
		WaitForSingleObject(h2, INFINITE);
		CloseHandle(h2);
		cerr << common << "," << res1 << "," << res2 << endl;
		assert(res1 + res2 == 3);
	}
}



